### ISSUE TITLE
Céges adatok a láblécbe

### ISSUE THREAD

**Issue by darabos** [darabos/megingat#33]
Ha megírod az adatokat, beteszem.

**Comment by darabos** [comment]
@megingat

**Comment by megingat** [comment]
"B-É" Könyvelő és Adótanácsadó Szolgáltató Betéti Társaság 
7461 Kaposvár-Toponár, Kócsag u 60.     (rövidesen változik majd Váci M. u 22.-re)
Adószáma:25222659-2-14
Cégjegyzék szám:14-06-300378

Gondolod, hogy elég a hivatalos rövid név? Mivel a címben az utcanév változni fog, most talán elég lenne a város...
"B-É" Bt.
7461 Kaposvár-Toponár
Adószáma:25222659-2-14
Cégjegyzék szám:14-06-300378

Jó lenne, ha ezt kisebb betűkkel lehetne írni, mint a neveinket és mondjuk alattunk egy hosszú sorban. 
Más: ugyanitt javasolják változtatni csak a nevemet: Dr. Darabosné M. Erzsébet -re :)

Köszönöm.

**Comment by megingat** [comment]
"B-É" Könyvelő és Adótanácsadó Szolgáltató Betéti Társaság
7461 Kaposvár-Toponár, Váci M. u 22.
Adószáma:25222659-2-14
Cégjegyzék szám:14-06-300378

Gondolod, hogy elég a _hivatalos_ rövid név?
"B-É" Bt.

Jó lenne, ha ezt a bordó sávban kisebb betűkkel lehetne írni, mint a
neveinket és mondjuk alattunk egy hosszú sorban.

Más: ugyanitt javasolják változtatni csak a nevemet: Dr. Darabosné M.
Erzsébet -re :)

Köszönöm.

2015-04-05 12:28 GMT+02:00 Daniel Darabos notifications@github.com:

**Comment by darabos** [comment]
Köszi! Betettem (https://github.com/darabos/megingat/commit/20b59e45fa5839037ef53bbdee2e97caf614b55d). Nagyon profi már a lábléc :).
